#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import argparse
from pathlib import Path
from PIL import Image

def die(msg, code=1):
    raise SystemExit(msg)

def hex_fmt(v, width):
    return f"${v:0{width}X}"

def find_full_match(out_rows, strip_rows):
    """Ritorna y se strip_rows coincide con out_rows[y:y+h], altrimenti None."""
    h = len(strip_rows)
    out_h = len(out_rows)
    max_y = out_h - h
    if max_y < 0:
        return None
    # Brute-force (h piccolo: tipicamente 16)
    for y in range(max_y + 1):
        ok = True
        for i in range(h):
            if out_rows[y + i] != strip_rows[i]:
                ok = False
                break
        if ok:
            return y
    return None

def match_tail_overlap(out_rows, strip_rows):
    """
    Se le prime (h-1) righe della striscia coincidono con le ultime (h-1) righe dell'output,
    ritorna k (= out_h-(h-1)), altrimenti None.
    """
    h = len(strip_rows)
    if h <= 1:
        return None
    out_h = len(out_rows)
    overlap = h - 1
    if out_h < overlap:
        return None
    start = out_h - overlap  # k
    for i in range(overlap):
        if out_rows[start + i] != strip_rows[i]:
            return None
    return start  # k

def pack_2bpp_nibbles(rows_bytes):
    """
    Impacchetta 2 pixel (4bpp indice 0..15) per byte:
    byte = (pix0<<4) | pix1
    Con larghezza 256 => 128 byte a riga.
    """
    out = bytearray()
    for row in rows_bytes:
        if len(row) != 256:
            die("Riga non larga 256: input/output non conforme.")
        # controllo indici
        # (evita costo alto: controlla a campione? Qui controlliamo tutto per sicurezza)
        for b in row:
            if b > 15:
                die("Trovato indice palette > 15: l'immagine non è a 16 colori (0..15).")
        for x in range(0, 256, 2):
            out.append((row[x] << 4) | row[x + 1])
    return bytes(out)

def write_asm_fieldmap(path, field_map, out_height):
    use_db = (out_height <= 256)
    directive = ".DB" if use_db else ".DW"
    width = 2 if use_db else 4

    lines = []
    lines.append("; Auto-generated by field_compactor.py")
    lines.append(f"; Output height = {out_height} lines")
    lines.append(f"; FieldMap[n] = ordinata (y) nell'immagine di output per la striscia che parte alla riga n")
    lines.append("")
    lines.append("FieldMap:")
    per_line = 16

    for i in range(0, len(field_map), per_line):
        chunk = field_map[i:i+per_line]
        vals = ", ".join(hex_fmt(v, width) for v in chunk)
        lines.append(f"    {directive} {vals}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

def write_c_fieldmap_h(path, field_map, out_height):
    """
    Richiesta: tipo u8. Tuttavia se out_height>256 (o max value >255) non ci sta in u8.
    In tal caso usiamo u16 (mantenendo nome FieldMap[]), così il file resta corretto.
    """
    maxv = max(field_map) if field_map else 0
    use_u8 = (out_height <= 256 and maxv <= 255)

    ctype = "u8" if use_u8 else "u16"
    guard = "FIELDMAP_H"

    # NOTA: non ridefiniamo u8/u16 per non interferire col progetto.
    # Se nel tuo progetto non sono definiti, puoi includere qui il tuo header tipi.
    lines = []
    lines.append("// Auto-generated by field_compactor.py")
    lines.append(f"// Output height = {out_height} lines, max FieldMap value = {maxv}")
    if not use_u8:
        lines.append("// NOTE: output > 256 righe (o valori >255), quindi FieldMap[] usa u16 per evitare overflow.")
    lines.append("")
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append("// Richiede che u8/u16 siano definiti nel progetto (es. typedef unsigned char u8; typedef unsigned short u16;)")
    lines.append("")
    lines.append(f"static const {ctype} FieldMap[{len(field_map)}] = {{")

    per_line = 16
    for i in range(0, len(field_map), per_line):
        chunk = field_map[i:i+per_line]
        vals = ", ".join(str(v) for v in chunk)
        lines.append(f"    {vals},")

    lines.append("};")
    lines.append("")
    lines.append(f"#endif // {guard}")
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")

def main():
    ap = argparse.ArgumentParser(
        description="Compatta verticalmente una PNG 256xL palettizzata 16 colori usando match di strisce 256xK e overlap K-1."
    )
    ap.add_argument("input_png", help="Immagine PNG di input (256xL, palettizzata a 16 colori)")
    ap.add_argument("--k", type=int, default=16, help="Altezza striscia K (default: 16)")
    ap.add_argument("--outdir", default="outdir", help="Cartella di output (default: outdir)")
    ap.add_argument("--prefix", default=None, help="Prefisso nome file output (default: nome del file input senza estensione)")
    args = ap.parse_args()

    in_path = Path(args.input_png)
    if not in_path.exists():
        die(f"File non trovato: {in_path}")

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    prefix = args.prefix if args.prefix else in_path.stem

    # Carica immagine
    img = Image.open(in_path)
    if img.size[0] != 256:
        die(f"Larghezza non valida: atteso 256, trovato {img.size[0]}")
    L = img.size[1]

    if img.mode != "P":
        die("L'immagine deve essere palettizzata (mode 'P'). Converti a PNG indicizzata a 16 colori prima di usare lo script.")

    pal = img.getpalette()
    if pal is None:
        die("Palette non trovata nell'immagine di input.")
    # Conteggio colori "attivi" non sempre affidabile; imponiamo indici 0..15 a runtime.

    K = args.k
    if K <= 0:
        die("K deve essere > 0.")

    # Estrai tutte le righe come bytes: ogni riga 256 bytes (indici palette)
    raw = img.tobytes()
    if len(raw) != 256 * L:
        die("Dimensione dati inattesa: immagine corrotta o non conforme.")
    input_rows = [raw[y*256:(y+1)*256] for y in range(L)]

    # Output costruito come lista di righe (bytes)
    out_rows = []
    field_map = [0] * L

    # n=0: scrivi striscia iniziale (altezza min(K, L))
    h0 = min(K, L - 0)
    out_rows.extend(input_rows[0:0+h0])
    field_map[0] = 0

    # Scorri tutte le ordinate n
    for n in range(1, L):
        h = min(K, L - n)  # se sfora, riduci: K = L-n (come richiesto)
        strip = input_rows[n:n+h]

        # 1) match completo in output
        y = find_full_match(out_rows, strip)
        if y is not None:
            field_map[n] = y
            continue

        # 2) match sulle ultime (h-1) righe dell'output -> append ultima riga
        kpos = match_tail_overlap(out_rows, strip)
        if kpos is not None:
            field_map[n] = kpos
            out_rows.append(strip[-1])  # aggiungi l'ultima riga
            continue

        # 3) nessun match: append intera striscia in coda
        start = len(out_rows)
        field_map[n] = start
        out_rows.extend(strip)

    out_h = len(out_rows)

    # Salva PNG output con la stessa palette
    out_img = Image.new("P", (256, out_h))
    out_img.putpalette(pal)
    out_img.frombytes(b"".join(out_rows))

    out_png = outdir / f"{prefix}_out.png"
    out_img.save(out_png, format="PNG")

    # Salva BIN (2 pixel per byte)
    out_bin = outdir / f"{prefix}.bin"
    packed = pack_2bpp_nibbles(out_rows)
    out_bin.write_bytes(packed)

    # Salva ASM FieldMap
    out_asm = outdir / "FieldMap.asm"
    write_asm_fieldmap(out_asm, field_map, out_h)

    # Salva C header FieldMap.h
    out_hfile = outdir / "FieldMap.h"
    write_c_fieldmap_h(out_hfile, field_map, out_h)

    # Messaggio finale
    print("OK.")
    print(f"Input:  {in_path}  (256x{L})")
    print(f"K:      {K}")
    print(f"Output: {out_png}  (256x{out_h})")
    print(f"BIN:    {out_bin}  ({len(packed)} bytes)")
    print(f"ASM:    {out_asm}")
    print(f"H:      {out_hfile}")
    print(f"Outdir: {outdir.resolve()}")

if __name__ == "__main__":
    main()
