// MSXgl | Raw files definitions generated by the Build tool

#define SPRITES_BIN_SEG 	768
#define SPRITES_BIN_REL 	0x0000
#define SPRITES_BIN_ABS 	0x600000
#define SPRITES_BIN_SIZE	0xF8000

#define FIELD_BIN_SEG 	252
#define FIELD_BIN_REL 	0x0000
#define FIELD_BIN_ABS 	0x1F8000
#define FIELD_BIN_SIZE	0x8000
