// MSXgl | Raw files definitions generated by the Build tool

#define SPRITES_BIN_SEG 	100
#define SPRITES_BIN_REL 	0x0000
#define SPRITES_BIN_ABS 	0xC8000
#define SPRITES_BIN_SIZE	0xE0000

#define FIELD_OUT_BIN_SEG 	230
#define FIELD_OUT_BIN_REL 	0x0000
#define FIELD_OUT_BIN_ABS 	0x1CC000
#define FIELD_OUT_BIN_SIZE	0x8000
